"""Add BG Stats play import metadata

Revision ID: 178823249fa5
Revises: 3c88fe2f727b
Create Date: 2026-08-24 13:01:08.545250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178823249fa5'
down_revision: Union[str, Sequence[str], None] = '3c88fe2f727b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plays', sa.Column('duration_minutes', sa.Integer(), nullable=True))
    op.add_column('plays', sa.Column('source', sa.String(length=20), server_default='app', nullable=False))
    op.add_column('plays', sa.Column('source_play_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint('uq_plays_source_play_id', 'plays', ['source', 'source_play_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_plays_source_play_id', 'plays', type_='unique')
    op.drop_column('plays', 'source_play_id')
    op.drop_column('plays', 'source')
    op.drop_column('plays', 'duration_minutes')
    # ### end Alembic commands ###
